### ISSUE TITLE
a feature request

### ISSUE THREAD

**Issue by RyoConcertina** [cylin743/concertina-abc-player#3]
Hello ck-san,

I am Ryo, the Concertina player.
Excuse me, it's been a while.

I'm currently working on creating tutorials using this tool.
I would like to make a feature request.

In the concertina, there are buttons that produce the same sound but cannot be selected solely by push and pull.
Specifically, these four buttons:

Right-hand push g: buttons 8 and **11** (counting from the top left)
Right-hand pull a: buttons 9 and **12**
Left-hand push G: buttons 10 and **13**
Left-hand pull A: buttons 10 and **13**

Currently, when I specify a right-hand push g, button 8 is automatically selected.
I would like to be able to specify those buttons individually.
For example, to specify button 11 with a right-hand push g, we could use "][2".

Thank you for your time and consideration.

**Comment by cylin743** [comment]
Thank you for your request. I'll add this feature ASAP.

**Comment by cylin743** [comment]
New feature released.
